export const recommendations = {
  "Light Drizzle": "",
  "Light Rain": "You would need a summer dress and umbrella.",
  "Light Snow": "",
  "Light Snow Grains": "",
  "Light Ice Crystals": "",
  "Light Ice Pellets": "",
  "Light Hail": "",
  "Light Mist": "",
  "Light Fog": "",
  "Light Fog Patches": "",
  "Light Smoke": "",
  "Light Volcanic Ash": "",
  "Light Widespread Dust": "",
  "Light Sand": "",
  "Light Haze": "",
  "Light Spray": "",
  "Light Dust Whirls": "",
  "Light Sandstorm": "",
  "Light Low Drifting Snow": "",
  "Light Low Drifting Widespread Dust": "",
  "Light Low Drifting Sand": "",
  "Light Blowing Snow": "",
  "Light Blowing Widespread Dust": "",
  "Light Blowing Sand": "",
  "Light Rain Mist": "",
  "Light Rain Showers": "",
  "Light Snow Showers": "",
  "Light Snow Blowing Snow Mist": "",
  "Light Ice Pellet Showers": "",
  "Light Hail Showers": "",
  "Light Small Hail Showers": "",
  "Light Thunderstorm": "",
  "Light Thunderstorms and Rain": "",
  "Light Thunderstorms and Snow": "",
  "Light Thunderstorms and Ice Pellets": "",
  "Light Thunderstorms with Hail": "",
  "Light Thunderstorms with Small Hail": "",
  "Light Freezing Drizzle": "",
  "Light Freezing Rain": "",
  "Light Freezing Fog": "",
  "Heavy Heavy Drizzle": "",
  "Heavy Rain": "",
  "Heavy Snow": "",
  "Heavy Snow Grains": "",
  "Heavy Ice Crystals": "",
  "Heavy Ice Pellets": "",
  "Heavy Hail": "",
  "Heavy Mist": "",
  "Heavy Fog": "",
  "Heavy Fog Patches": "",
  "Heavy Smoke": "",
  "Heavy Volcanic Ash": "",
  "Heavy Widespread Dust": "",
  "Heavy Sand": "",
  "Heavy Haze": "",
  "Heavy Spray": "",
  "Heavy Dust Whirls": "",
  "Heavy Sandstorm": "",
  "Heavy Low Drifting Snow": "",
  "Heavy Low Drifting Widespread Dust": "",
  "Heavy Low Drifting Sand": "",
  "Heavy Blowing Snow": "",
  "Heavy Blowing Widespread Dust": "",
  "Heavy Blowing Sand": "",
  "Heavy Rain Mist": "",
  "Heavy Rain Showers": "",
  "Heavy Snow Showers": "",
  "Heavy Snow Blowing Snow Mist": "",
  "Heavy Ice Pellet Showers": "",
  "Heavy Hail Showers": "",
  "Heavy Small Hail Showers": "",
  "Heavy Thunderstorm": "",
  "Heavy Thunderstorms and Rain": "",
  "Heavy Thunderstorms and Snow": "",
  "Heavy Thunderstorms and Ice Pellets": "",
  "Heavy Thunderstorms with Hail": "",
  "Heavy Thunderstorms with Small Hail": "",
  "Heavy Freezing Drizzle": "",
  "Heavy Freezing Rain": "",
  "Heavy Freezing Fog": "",
  "Patches of Fog": "",
  "Shallow Fog": "",
  "Partial Fog": "",
  "Overcast": "",
  "Clear": "You would need a summer dress, summer hat and sunglasses.",
  "Partly Cloudy": "You would need a summer dress.",
  "Mostly Cloudy": "You would need a pullover, winter hat, gloves, warm scarf and heavy coat.",
  "Scattered Clouds": "",
  "Small Hail": "",
  "Squalls": "",
  "Funnel Cloud": "",
  "Unknown Precipitation": "",
  "Unknown": ""
};
